<?php  //[STAMP] 5a9f85140359b929d1dbe58b518df296
namespace NSWDPC\Chimple\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
