# github action that checks code with Rector
name: Rector

on:
  pull_request: null

jobs:
  rector:
    name: Rector
    # reference to re-usable workflow
    uses: nswdpc/ci-files/.github/workflows/rector.yml@main
    secrets: inherit
