# github action that checks code with Rector
name: Rector

on:
    pull_request: null

jobs:
    rector:
        runs-on: ubuntu-latest
        if: github.event.pull_request.head.repo.full_name == 'nswdpc/silverstripe-chimple'
        steps:
            -
                name: 'Prep'
                if: github.event.pull_request.head.repo.full_name == github.repository
                uses: actions/checkout@v4
                with:
                    # Must be used to trigger workflow after push
                    token: ${{ secrets.ACCESS_TOKEN }}

            -
                name: 'Setup PHP'
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.3
                    tools: composer:v2
                    coverage: none

            -
                name: 'Composer'
                run: |
                    composer config --no-plugins allow-plugins.composer/installers true
                    composer config --no-plugins allow-plugins.silverstripe/recipe-plugin true
                    composer config --no-plugins allow-plugins.silverstripe/vendor-plugin true
                    composer config --no-plugins allow-plugins.phpstan/extension-installer true
                    composer install --ansi --no-interaction --no-progress

            -
                name: 'Rector'
                run: vendor/bin/rector --debug --ansi --config .rector.dist.php
                # @todo apply coding standard if used

            -
                # commit only to core contributors who have repository access
                name: 'Commit action'
                uses: stefanzweifel/git-auto-commit-action@v5
                with:
                    commit_message: '[rector] Rector fixes'
                    commit_author: 'GitHub Action <actions@github.com>'
                    commit_user_email: 'action@github.com'
